version: '3.8'

services:
  # API backend
  lumo.api:
    image: ${DOCKER_REGISTRY-}lumoapi
    container_name: lumo.api
    build:
      context: .
      dockerfile: Lumo.Api/Dockerfile
    depends_on:
      lumo.db:
        condition: service_healthy
      idprovider:
        condition: service_started
    networks:
      - lumo_network
    environment:
      # Database Connection
      - CONNECTIONSTRINGS__DEFAULT=${LUMO_DB_CONNECTION}
      
      # Authentication Configuration
      - Authentication__Audience=${Authentication_AUDIENCE}
      - Authentication__ValidIssuer=${Authentication_VALID_ISSUER}
      - Authentication__MetadataUrl=${AUTHETICATION_METADATA_URL}
      - Authentication__RequireHttpsMetadata=false
      
      # Keycloak Configuration
      - Keycloak__BaseUrl=${KEYCLOAK_BASE_URL}
      - Keycloak__AdminUrl=${KEYCLOAK_ADMIN_URL}
      - Keycloak__TokenUrl=${KEYCLOAK_TOKEN_URL}
      - Keycloak__AdminClientId=${KEYCLOAK_ADMIN_CLIENT_ID}
      - Keycloak__AdminClientSecret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - Keycloak__AuthClientId=${KEYCLOAK_AUTH_CLIENT_ID}
      - Keycloak__AuthClientSecret=${KEYCLOAK_AUTH_CLIENT_SECRET}
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Lumo.Infrastructure.Authentication=Debug
      

 # Set up postgres database
  lumo.db:
    image: postgres:17
    container_name: lumo.db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - lumo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_LOGIN_BANNER="Lumo Blog Database Admin"
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=10
      - PGADMIN_CONFIG_LOGIN_LOCKOUT_TIME=30
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - lumo.db
    volumes:
      - ./.containers/pgadmin:/var/lib/pgadmin
    networks:
      - lumo_network

  # Identity Provider configuration
  # Setup Keycloak
  idprovider:
    image: quay.io/keycloak/keycloak:26.3
    command: start --import-realm
    container_name: lumo.keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://lumo.db:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      lumo.db:
        condition: service_healthy
    networks:
      - lumo_network
    volumes:
      - ./.containers/keycloak:/opt/keycloak/data
      - ./.file/import/lumoblog-realm-export.json:/opt/keycloak/data/import/lumoblog-realm-export.json
      
networks:
  lumo_network:
    driver: bridge